export const START_FETCHING_DRIVERS = 'START_FETCHING_DRIVERS';
export const LOAD_DRIVERS = 'LOAD_DRIVERS';
export const DELETE_DRIVER = 'DELETE_DRIVER';
export const CHANGE_FILTER = 'CHANGE_FILTER';

export const START_FETCHING_TASKS = 'START_FETCHING_TASKS';
export const LOAD_TASKS = 'LOAD_TASKS';
export const ASSIGN_TASK = 'ASSIGN_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';

export const CHANGE_CENTER = 'CHANGE_CENTER';